# Generated by Django 4.2.7 on 2023-11-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_group_leader_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='movie',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
