# Generated by Django 4.2.7 on 2023-11-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='score',
            field=models.IntegerField(default=5000),
        ),
    ]
